version: "3"

services:
  app:
    container_name: releazar
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file: .env
    environment:
      RAILS_ENV: development

  postgres:
    image: postgres
    container_name: database
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
      - /var/run/postgresql:/var/run/postgresql
