default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DATABASE_USER'] %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>
  host: <%= ENV['DATABASE_HOST'] %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: releazar_development
test:
  <<: *default
  database: releazar_test
production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
